export enum ModelType {
  bank = 'bank',
  code = 'code',
  codelist = 'codelist',
  inheritedBank = 'inheritedBank',
  need = 'need',
  prefilledResponse = 'prefilledResponse',
  prefilledResponseProduct = 'prefilledResponseProduct',
  product = 'product',
  publication = 'publication',
  requirement = 'requirement',
  requirementAnswer = 'requirementAnswer',
  response = 'response',
  responseProduct = 'responseProduct',
  specification = 'specification',
  specificationGeneralProduct = 'specificationGeneralProduct',
  specificationProduct = 'specificationProduct',
  tag = 'tag',
  variant = 'variant',
}
