export enum QuestionVariant {
  Q_CHECKBOX = 'Q_CHECKBOX',
  Q_CODELIST = 'Q_CODELIST',
  Q_CONFIRMATION = 'Q_CONFIRMATION',
  Q_FILEUPLOAD = 'Q_FILEUPLOAD',
  Q_PERIOD_DATE = 'Q_PERIOD_DATE',
  Q_SLIDER = 'Q_SLIDER',
  Q_TEXT = 'Q_TEXT',
  Q_TIME = 'Q_TIME',
}
