name: Continuous Deployment

on:
  push:
    branches:
      - develop
      - krb-*
      - KRB-*

env:
  AZURE_WEBAPP_NAME: krb-webclient # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'build' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'

jobs:
  Build_and_Deploy_to_Azure_Dev:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint
        shell: bash
        run: npm run-script lint:ci

      - name: Test
        shell: bash
        run: npm run-script test --coverage

      - name: Build
        run: npm run-script build
        env:
          REACT_APP_CLIENTID: ${{ secrets.REACT_APP_CLIENTID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_DEV }}
          CI: false

      # Steps triggered only on develop branch

      - name: Sonarcube
        if: github.ref == 'refs/heads/develop'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        if: github.ref == 'refs/heads/develop'
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
