name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.17.0-chrome106
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - run: npx cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: npm run-script build:ci

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.17.0-chrome106
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Cypress info
        run: npx cypress info

      - name: Node info
        run: node -v

      - name: __e Dir
        run: ls /__e

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/*
          config-file: cypress.config.ts
        env:
          REACT_APP_CLIENTID: ${{ secrets.REACT_APP_CLIENTID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_DEV }}